// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ugtyjknypdkwcqudwqyh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVndHlqa255cGRrd2NxdWR3cXloIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTczOTQ2NTAsImV4cCI6MjA3Mjk3MDY1MH0.Ig5lLu2fXD59M9FNzNBTBvHLI6Ksvk-KKvM1WxQBenI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});